### ISSUE TITLE
Error when starting storybook after installing Creevey

### ISSUE THREAD

**Issue by varya** [wKich/creevey#105]
![2021-01-08_10-33-12](https://user-images.githubusercontent.com/27215/103997351-a3873b80-51a3-11eb-8b5a-e41b894b2d9b.png)

I have 2 clones of the same project. One has this error.

The difference is that on the working clone creevey is 0.7.14, on the broken one it is 0.7.17.

**Comment by wKich** [comment]
Oh, sorry for what. I tried to fix but with parameters. And completely forgot, that imported function couldn't exist in different versions. I'll release fix soon

**Comment by wKich** [comment]
Released 0.7.18. please, check it.

**Comment by varya** [comment]
Checked with creevey@7.20.0. Storybook starts. thanks!
