### ISSUE TITLE
Creevey does not run on Windows machine

### ISSUE THREAD

**Issue by varya** [wKich/creevey#106]
I am trying to set up Creevey at my project, and on Mac it works nicely. But my colleague with Windows have errors like the following. Our guess is that it has something to do with system security restrictions (which unfortunately cannot be changed).

If this is the problem, the possible solution would be to run needed docker containers separately in admin mode (we did the same for another testing setup). In Creevey documentation I could not find information related to the issue.

Is there any suggestion how to fix? 

![error](https://user-images.githubusercontent.com/27215/104011672-2b2a7580-51b7-11eb-90d6-b1f48a45f9e8.png)

**Comment by wKich** [comment]
Solution https://www.reddit.com/r/docker/comments/grjwl9/comment/frztfhk
