### ISSUE TITLE
Problems with skip options

### ISSUE THREAD

**Issue by vandal-x** [wKich/creevey#12]
Hi everyone!

I have some problems with `skip` option. Here is my config:
```
addDecorator(
  withCreevey({
    captureElement: TEST_CSS_SELECTOR,
    skip: { kinds: ["Editor"] }
  })
);
```
I expected to skip stories with "Editor" name, but instead it's locked all my stories.
![image](https://user-images.githubusercontent.com/22432062/70971861-bd02a480-20c3-11ea-96db-60db151ba893.png)

Any help?

**Comment by wKich** [comment]
Fixed in 0.2.3
