### ISSUE TITLE
error if a filename starts with "creevey.config.js"

### ISSUE THREAD

**Issue by antonellopasella** [wKich/creevey#120]
If we have a file named "creevey.config.js.js" the script fails.

I think the filename is checked only for starts and not for and exact match

**Comment by wKich** [comment]
@antonellopasella, hello. Thank you for the report. Can I wonder, why you named the file with `.js.js` extension?

**Comment by antonellopasella** [comment]
I was renaming with VSCode and it doubled the extension 😅

**Comment by wKich** [comment]
Ah, ok :)
I'll fix it.

**Comment by wKich** [comment]
Fixed in 0.7.28
