### ISSUE TITLE
can't selectStory in IE.

### ISSUE THREAD

**Issue by kps-s-wada** [wKich/creevey#139]
creevey@0.7.26

https://github.com/wKich/creevey/blob/master/src/server/selenium/browser.ts#L306

This line is not transpiled.
IE doesn't support object spread syntax, so it doesn't work.

**Comment by wKich** [comment]
Hi. Nice catch  👍. Thank you for reporting. I'll fix it today.

**Comment by wKich** [comment]
@kps-s-wada, I've released 0.7.27 with IE fix. Please give it to try.

**Comment by wKich** [comment]
Closed because of inactivity
