### ISSUE TITLE
Skipping mdx stories?

### ISSUE THREAD

**Issue by 9inpachi** [wKich/creevey#141]
Hi,

Just wanted to ask if there's a way to skip mdx stories?

**Comment by 9inpachi** [comment]
For a story `introduction.stories.mdx` with `<Meta title="Documentation/Introduction" />`, it gives this error.

```
[FAIL:chrome:69453] "before each" hook: switchStory for "Page" 
   Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
```

**Comment by wKich** [comment]
Hi. Thank you for reporting. Could you please share what's inside the `introduction.stories.mdx`? It helps me to fix this case

Yes, you can skip any story you want.
For this one, you need to add global storybook parameters into `.storybook/preview.js` file. Like this:

```js
export const parameters = {
  creevey: {
    skip: { kinds: ['Documentation/Introduction'] }
  }
}
```
The more information about the skip option you can find [here](https://github.com/wKich/creevey/blob/master/docs/config.md#skip-option-examples)

**Comment by wKich** [comment]
It looks like this file doesn't contain any `<Story />` element

**Comment by 9inpachi** [comment]
> Yes, you can skip any story you want.
For this one, you need to add global storybook parameters into .storybook/preview.js file. Like this:

Interesting! I was trying to find a way to do it through both storybook (through the addons configuration) and Creevey but couldn't get around it. This really helps. Thanks a lot!

> It looks like this file doesn't contain any <Story /> element

Indeed, that's true. We are using some mdx files as purely docs without any component stories in them but we do have some components in them. I think it should be possible to have it included without any `<Story />` in the Creevey tests. Or may be totally exclude mdx files that do not have any component story (`<Story />`) in them.

All in all, your suggestion really helps and also, of course, **thank you for creating and maintaining Creevey**!
