### ISSUE TITLE
How to handle waiting for async content?

### ISSUE THREAD

**Issue by ArthurClemens** [wKich/creevey#144]
I have a page where some content is loaded from the network. The generated screenshot shows white parts, until I repeatedly click the play button to generate the screenshot again. 

What is the recommended approach?

**Comment by wKich** [comment]
@ArthurClemens, hi. There are two ways how to deal with async stories:
- Use Storybook loaders https://storybook.js.org/docs/react/writing-stories/loaders to prefetch data
- Define story parameter `creevey: { waitForReady: true }` and then call `window.__CREEVEY_SET_READY_FOR_CAPTURE__?.()` when you think the content is loaded

**Comment by ArthurClemens** [comment]
Great, I'll explore these.
