### ISSUE TITLE
"" value for skip should mean true

### ISSUE THREAD

**Issue by varya** [wKich/creevey#147]
This
```
creevey: {
    skip: ""
  }
```
equals to

```
creevey: {
    skip: false
  }
```

I think it has to be equal to `true`. Especially from the workflow perspective. I might want to have a reason for skipping but I don't YET have exact wording for it.

**Comment by wKich** [comment]
The empty string is a falsy value. So if you don't have a reason yet it might be ok to set `true`. It's more intuitive than an empty string, but the problem is the skip types accept only `string | SkipOption | SkipOption[]`
