### ISSUE TITLE
"Cannot use import statement outside a module", creevey doesn't see stories

### ISSUE THREAD

**Issue by varya** [wKich/creevey#154]
In this repo, https://github.com/goright-io/hands-on-design-system

I am having the following error

![2021-05-27_14-40-32](https://user-images.githubusercontent.com/27215/119819986-acca3800-bef9-11eb-9bbe-d70223996e63.png)

There was no such error in other projects, and the storybook seems to be the same version. Could it be some version mismatch?

**Comment by wKich** [comment]
I'll take a look, thanks for the report

**Comment by wKich** [comment]
Fixed in 0.7.30
