### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\User\myproject\report\tests.json'

### ISSUE THREAD

**Issue by Sm1t** [wKich/creevey#157]
Hi, thanks for this awesome project! I am trying to use it in my project and I am getting the following error:
![image](https://user-images.githubusercontent.com/22860327/121189795-e13bdd80-c883-11eb-80be-c177d7c80acd.png)

It seems to me that before writing the file, you need to check if such a path exists. I fixed this by manually creating the "report" directory.

**Comment by wKich** [comment]
Hi, yeah, I already fixed this error but forgot to release a new version. Sorry for that. I'll release 0.7.30 today

**Comment by wKich** [comment]
@Sm1t, done. Thank you for your supporting

**Comment by Sm1t** [comment]
It works, thanks!
