### ISSUE TITLE
UnknownCommandError: Unrecognized command: actions - Saucelabs setup

### ISSUE THREAD

**Issue by Perni1984** [wKich/creevey#158]
I am currently testing creevy with a bigger project and so far it works very well. Locally all tests run through smoothly, but when I am trying to connect to our saucelabs selenium grid over the saucelabs connect proxy I am receiving  the following `UnknownCommandError: Unrecognized command: actions` error:

![image](https://user-images.githubusercontent.com/9039956/121393428-9e940700-c950-11eb-9a1b-869c4cd771f2.png)

Does somebody have some hint for me or has somebody a working setup with saucelabs and creevey?

**Comment by wKich** [comment]
Hi, thanks for reporting.

Could you share your creevey config that you use for saucelabs? I'll try to investigate the issue. I think it could be bad version compatibility between selenium and chrome webdriver.

**Comment by Perni1984** [comment]
@wKich I think this problem is not related with creevey, but more to my saucelabs config. I will close the issue now and eventually reopen if I know more.
