### ISSUE TITLE
Tests started to fail randomly

### ISSUE THREAD

**Issue by bentleyvk** [wKich/creevey#163]
Hi, thank you for this great lib you made!
Today almost all our tests started to fail locally and in GitHub Actions.
All the failures looks the same:
![image](https://user-images.githubusercontent.com/36186912/123096625-f7c36680-d437-11eb-9907-1440d17da3ab.png)

We are using v0.7.29.

Any ideas what can be the cause? I looked at `selenoid` and it seems haven't changed since March.

**Comment by wKich** [comment]
Hi. Thank you for your feedback. 
By default if you didn't specify browser version, creevey will check the latest browser docker image. So it looks like image had been updated. According by this page https://hub.docker.com/r/selenoid/chrome/tags?page=1&ordering=last_updated chrome updated 3 hours ago.

**Comment by mayank99** [comment]
If you look at that page again, the last update was actually 7 days ago. For some reason, the "latest" tag was only updated today.
<img src="https://user-images.githubusercontent.com/9084735/123125747-cb4b2280-d416-11eb-8ef9-31b0e912b755.png" width="30%" />

I investigated a bit more and found this issue: https://github.com/aerokube/images/issues/399

Apparently, the "latest" tag was previously using version 88.0 from a few months ago.

**Comment by wKich** [comment]
Yeah, it could be a reason why screenshots start failing. And it's ok, from version to version browser developers might change how UI is render. You would like to specify exact browser version and updated it explicitly.

**Comment by wKich** [comment]
@bentleyvk, I checked my own tests, they also failing because of rendering changes
![image](https://user-images.githubusercontent.com/6397708/123388584-63c9da00-d5b2-11eb-8c8f-6cf2faaad4ab.png)
It's definitely browser rendering related thing

**Comment by bentleyvk** [comment]
@wKich thank you for response. Maybe it is worth adding to your readme or other documentation about this.
