### ISSUE TITLE
feat: ci mode, exiting after first fail

### ISSUE THREAD

**Issue by dargmuesli** [wKich/creevey#167]
Hey there, great plugin!
I want to feature request a "CI" mode that make creevey exit on first error with a status code indicating failure. This way not all other images have to be checked and CI server time is saved.

**Comment by wKich** [comment]
@dargmuesli, Hi. Thanks for the request. Sounds reasonable for some cases. I'll try to add an option for that.

**Comment by wKich** [comment]
Added `failFast` CLI option in 0023bbb. I'll release a new version soon.

**Comment by wKich** [comment]
@dargmuesli released 0.7.33

**Comment by dargmuesli** [comment]
Great, thanks! It works for me when specifying `--failFast` as command line parameter, but not when setting `failFast: true` in the `creevey.config.js`, is that intended? In the config file I could use `process.env.CI` or somethink alike to detect whether failFast mode should be active or not. I'm sure that would work on the command line too somehow, but that would surely look like more of a hacky solution, as far as I know command line stuff.

**Comment by wKich** [comment]
@dargmuesli oh, sorry. I thought only about cli option. I'll add it to config and release new version

**Comment by dargmuesli** [comment]
No worries, thanks for the quick responses! You're doing great work.

**Comment by wKich** [comment]
@dargmuesli done, 0.7.34. And thank you for your kind words

**Comment by dargmuesli** [comment]
Great, implemented: https://github.com/maevsi/maevsi/blob/17afec6b674a438eea22d3da0fed844e44811eaa/nuxt/.storybook/creevey/creevey.config.js#L15 :partying_face:
