### ISSUE TITLE
Recommended way to disable animations in creevey

### ISSUE THREAD

**Issue by Perni1984** [wKich/creevey#168]
Currently I am fighting with some flaky tests in a larger project and I am wondering what @wKich would recommend as a way to disable web animations in the storybooks?

Is there something along the lines like https://github.com/reg-viz/storycap/issues/8 for creevey?

**Comment by wKich** [comment]
@Perni1984 Creevey disables animations out-of-the-box. It happens here https://github.com/wKich/creevey/blob/8431918656378b6760a60da8570fb18952de210c/src/client/addon/withCreevey.ts#L164
Creevey creates a stylesheet with these styles https://github.com/wKich/creevey/blob/8431918656378b6760a60da8570fb18952de210c/src/client/addon/withCreevey.ts#L71-L81
Also, it hides the blinking cursor in inputs.

Do you have any issues? These styles don't stop js or gif animations, only the css, and transitions.

I think there is one case when it will not work if the story refreshes the page for some reason. But it's a weird case.

**Comment by Perni1984** [comment]
@wKich supercool that css animations are disabled automatically. I had some flaky tests and suspected animations, but as it seems we are changing state quite fast and thus rerendering the component in the story and sometimes the screenshot get's taken before the state change and sometimes after.

**Comment by wKich** [comment]
@Perni1984 You can use `waitForReady` flag in creevey story parameters and call global callback when you think, that story is ready for capturing. I'll write example in docs later. But you can see usage:
Where describe `waitForReady` parameter
https://github.com/wKich/creevey/blob/945a258ee67f8c80228f3f4c4df80c3340bfba9e/stories/BlendView.stories.tsx#L13
And execution of global callback
https://github.com/wKich/creevey/blob/945a258ee67f8c80228f3f4c4df80c3340bfba9e/src/client/shared/components/ImagesView/BlendView.tsx#L45-L47

I know it's not ideal, but it solves the case when your component or story updates after the first render
