### ISSUE TITLE
`ssh2` vulnerable version through `docker-modem`

### ISSUE THREAD

**Issue by bentleyvk** [wKich/creevey#186]
Dependabot found that `creevey` has vulnerable `ssh2` version that comes from `docker-modem`.
https://github.com/advisories/GHSA-652h-xwhf-q4h6
![image](https://user-images.githubusercontent.com/36186912/134877829-1bb6a800-9f80-4dc2-857f-2d91a5e8a5a4.png)

I see that `docker-modem` has fixed this issue in path release `3.0.3`: https://github.com/apocas/docker-modem/commit/0b24b61f4a92ab4dcc8bd3e4b3c49e279eec8af0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by wKich** [comment]
@bentleyvk Thanks for opening the issue. I updated deps and released 0.7.38
