### ISSUE TITLE
 Cannot start test with a service like BrowserStack.

### ISSUE THREAD

**Issue by kps-s-wada** [wKich/creevey#52]
Hello.

I tried to do a multi-browser test using a service like BrowserStack.

However, due to the limited number of BrowserStack parallel connections, Creevey did not start.

Creevey connects in parallel with all registered Selenium nodes.

In a situation where the number of connections is limited, I think the following considerations are necessary.

1. Do not connect to Selenium Grid at UI startup. Connect when running the test.
2. Limit the number of connections to the Hub.
3. Sort the test execution order by browser(Because it costs a lot to start Node).

**Comment by wKich** [comment]
Hello. I'm really sorry for late response 😅 

Yeah, I understand that BrowserStack has pretty limited number of parallel sessions.

The reason why creevey start all sessions on startup is allow to start tests immediately especially if you start/restart tests from UI runner, and it's allow don't waste time on reconnect between tests.

I think, I could add option to limit total connections count, and utilize between tests more properly.


PS. I recommend you try to use next version 0.7.0 from beta channel. If you don't need to run tests on IE/Safari or mobile browers, you might run tests in docker without BrowserStack limitation.

**Comment by wKich** [comment]
Please, free to contact me if you have any questions. I'll glad to help.

**Comment by wKich** [comment]
In some 0.7.x version I added the ability to use browserstack or any other remote grid for specific browsers and run other browsers in docker simultaneously
