### ISSUE TITLE
SyntaxError when starting creevey

### ISSUE THREAD

**Issue by Raykeen** [wKich/creevey#79]
After updating 0.0.30 -> 0.6.4 I've got the error at start.
storybook version - 5.3.17

> [FAIL:28188] C:\billy\frontend-tasks\docs\node_modules\@babel\runtime\helpers\esm\inheritsLoose.js:1
> export default function _inheritsLoose(subClass, superClass) {
> ^^^^^^
> 
> SyntaxError: Unexpected token export
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at eval (webpack:///external_%22@babel/runtime/helpers/esm/inheritsLoose%22?:1:18)
>     at Object.@babel/runtime/helpers/esm/inheritsLoose (C:\billy\frontend-tasks\docs\report\storybook\storybook.js:19860:1)
>     at __webpack_require__ (C:\billy\frontend-tasks\docs\report\storybook\storybook.js:20:30)
> [FAIL:28188] TypeError: Cannot set property 'innerHTML' of null
>     at showErrorDisplay (C:\billy\frontend-tasks\docs\node_modules\@storybook\core\dist\client\preview\start.js:131:62)
>     at showException (C:\billy\frontend-tasks\docs\node_modules\@storybook\core\dist\client\preview\start.js:162:3)
>     at StoryStore.renderUI (C:\billy\frontend-tasks\docs\node_modules\@storybook\core\dist\client\preview\start.js:431:9)
>     at StoryStore.emit (C:\billy\frontend-tasks\docs\node_modules\eventemitter3\index.js:201:33)
>     at Timeout._onTimeout (C:\billy\frontend-tasks\docs\node_modules\@storybook\client-api\dist\story_store.js:357:16)
>     at ontimeout (timers.js:436:11)
>     at tryOnTimeout (timers.js:300:5)
>     at listOnTimeout (timers.js:263:5)
>     at Timer.processTimers (timers.js:223:10)
> error Command failed with exit code 4294967295.

**Comment by wKich** [comment]
Hi. Try to use creevey@next. I'll take a look why this happened

**Comment by Raykeen** [comment]
0.7 fixes the issue, thank you
